<? 
ini_set('auto_detect_line_endings',TRUE);
include "connect.php"; 

$res = db_query_first_cell( "select BillboardName from songs limit 1" );
echo( "BillboardNamefrom: $res<Br>" );
$res = db_query_first_cell( "select BillboardArtistName from songs limit 1" );
echo( "BillboardArtistNamefrom: $res<Br>" );

$res = db_query_first_cell( "select OverallRepetitiveness                   from songs limit 1" );
echo( "OverallRepetitiveness: $res<Br>" );
$res = db_query_first_cell( "select ConsonanceAlliterationScore             from songs limit 1" );
echo( "ConsonanceAlliterationScore: $res<Br>" );
$res = db_query_first_cell( "select AssonanceAlliterationScore              from songs limit 1" );
echo( "AssonanceAlliterationScore: $res<Br>" );
$res = db_query_first_cell( "select MainMelodicRange                        from songs limit 1" );
echo( "MainMelodicRange: $res<Br>" );
$res = db_query_first_cell( "select PercentDiatonicChords                   from songs limit 1" );
echo( "PercentDiatonicChords: $res<Br>" );
$res = db_query_first_cell( "select IsTonalParallelMixture                  from songs limit 1" );
echo( "IsTonalParallelMixture: $res<Br>" );
$res = db_query_first_cell( "select AmountOfDistinctParts                   from songs limit 1" );
echo( "AmountOfDistinctParts: $res<Br>" );
$res = db_query_first_cell( "select Timbre                                  from songs limit 1" );
echo( "Timbre: $res<Br>" );
$res = db_query_first_cell( "select WordsRepetitionPrevalence               from songs limit 1" );
echo( "WordsRepetitionPrevalence: $res<Br>" );
$res = db_query_first_cell( "select LineRepetitionPrevalence                from songs limit 1" );
echo( "LineRepetitionPrevalence: $res<Br>" );
$res = db_query_first_cell( "select SlangWords                              from songs limit 1" );
echo( "SlangWords: $res<Br>" );
$res = db_query_first_cell( "select ThousandWordsPrevalence                 from songs limit 1" );
echo( "ThousandWordsPrevalence: $res<Br>" );
$res = db_query_first_cell( "select TenThousandWordsPrevalence              from songs limit 1" );
echo( "TenThousandWordsPrevalence: $res<Br>" );
$res = db_query_first_cell( "select FiftyThousandWordsPrevalence            from songs limit 1" );
echo( "FiftyThousandWordsPrevalence: $res<Br>" );
$res = db_query_first_cell( "select PercentAbbreviations                    from songs limit 1" );
echo( "PercentAbbreviations: $res<Br>" );
$res = db_query_first_cell( "select PercentNonDictionary                    from songs limit 1" );
echo( "PercentNonDictionary: $res<Br>" );
$res = db_query_first_cell( "select PercentNonProfanity                     from songs limit 1" );
echo( "PercentNonProfanity: $res<Br>" );
$res = db_query_first_cell( "select RhymeDensity                            from songs limit 1" );
echo( "RhymeDensity: $res<Br>" );
$res = db_query_first_cell( "select RhymesPerSyllable                       from songs limit 1" );
echo( "RhymesPerSyllable: $res<Br>" );
$res = db_query_first_cell( "select RhymesPerLine                           from songs limit 1" );
echo( "RhymesPerLine: $res<Br>" );
$res = db_query_first_cell( "select NumberOfRhymeGroupsELR                  from songs limit 1" );
echo( "NumberOfRhymeGroupsELR: $res<Br>" );
$res = db_query_first_cell( "select VocalsInstrumentsPrevalence             from songs limit 1" );
echo( "VocalsInstrumentsPrevalence: $res<Br>" );
$res = db_query_first_cell( "select VocalPostChorusCount                    from songs limit 1" );
echo( "VocalPostChorusCount: $res<Br>" );
$res = db_query_first_cell( "select UseOfABridge                            from songs limit 1" );
echo( "UseOfABridge: $res<Br>" );
$res = db_query_first_cell( "select PersonReferences                        from songs limit 1" );
echo( "PersonReferences: $res<Br>" );
$res = db_query_first_cell( "select LocationReferences                      from songs limit 1" );
echo( "LocationReferences: $res<Br>" );
$res = db_query_first_cell( "select OrganizationorBrandReferences           from songs limit 1" );
echo( "OrganizationorBrandReferences: $res<Br>" );
$res = db_query_first_cell( "select ConsumerGoodsReferences                 from songs limit 1" );
echo( "ConsumerGoodsReferences: $res<Br>" );
$res = db_query_first_cell( "select CreativeWorksTitles                     from songs limit 1" );
echo( "CreativeWorksTitles: $res<Br>" );
$res = db_query_first_cell( "select EndLinePerfectRhymesPercentage          from songs limit 1" );
echo( "EndLinePerfectRhymesPercentage: $res<Br>" );
$res = db_query_first_cell( "select EndLineSecondaryPerfectRhymesPercentage from songs limit 1" );
echo( "EndLineSecondaryPerfectRhymesPercentage: $res<Br>" );
$res = db_query_first_cell( "select EndLineAssonanceRhymePercentage         from songs limit 1" );
echo( "EndLineAssonanceRhymePercentage: $res<Br>" );
$res = db_query_first_cell( "select PerfectRhymesPercentage                 from songs limit 1" );
echo( "PerfectRhymesPercentage: $res<Br>" );
$res = db_query_first_cell( "select AssonanceRhymePercentage                from songs limit 1" );
echo( "AssonanceRhymePercentage: $res<Br>" );
$res = db_query_first_cell( "select ConsonanceRhymePercentage               from songs limit 1" );
echo( "ConsonanceRhymePercentage: $res<Br>" );
$res = db_query_first_cell( "select EndOfLineRhymesPercentage               from songs limit 1" );
echo( "EndOfLineRhymesPercentage: $res<Br>" );
$res = db_query_first_cell( "select MidLineRhymesPercentage                 from songs limit 1" );
echo( "MidLineRhymesPercentage: $res<Br>" );
$res = db_query_first_cell( "select InternalRhymesPercentage                from songs limit 1" );
echo( "InternalRhymesPercentage: $res<Br>" );    
$res = db_query_first_cell( "select MidWordRhymes                           from songs limit 1" );
echo( "MidWordRhymes: $res<Br>" );
$res = db_query_first_cell( "select WordsPerLineAvg                         from songs limit 1" );
echo( "WordsPerLineAvg: $res<Br>" );
$res = db_query_first_cell( "select ChordDegreePrevalence               from songs limit 1" );
echo( "ChordDegreePrevalence: $res<Br>" );
$res = db_query_first_cell( "select MelodicThemeRepetitions                 from songs limit 1" );
echo( "MelodicThemeRepetitions: $res<Br>" );
$res = db_query_first_cell( "select HSDsongid                               from songs limit 1" );
echo( "HSDsongid: $res<Br>" );
$res = db_query_first_cell( "select PreChorusSectionLyrics                  from songs limit 1" );
echo( "PreChorusSectionLyrics: $res<Br>" );
$res = db_query_first_cell( "select MyPartID                                from songs limit 1" );
echo( "MyPartID: $res<Br>" );
$res = db_query_first_cell( "select MainMelodicRangeNum                     from songs limit 1" );
echo( "MainMelodicRangeNum: $res<Br>" );
$res = db_query_first_cell( "select UseofParallelMode                       from songs limit 1" );
echo( "UseofParallelMode: $res<Br>" );
$res = db_query_first_cell( "select ProductionMood                          from songs limit 1" );
echo( "ProductionMood: $res<Br>" );
$res = db_query_first_cell( "select ChordRepetition                         from songs limit 1" );
echo( "ChordRepetition: $res<Br>" );
$res = db_query_first_cell( "select UseOfTriads                             from songs limit 1" );
echo( "UseOfTriads: $res<Br>" );
$res = db_query_first_cell( "select UseOfInvertedChords                     from songs limit 1" );
echo( "UseOfInvertedChords: $res<Br>" );
$res = db_query_first_cell( "select AverageWordRepetition                   from songs limit 1" );
echo( "AverageWordRepetition: $res<Br>" );
$res = db_query_first_cell( "select LiteralExperiencesvsAbstract            from songs limit 1" );
echo( "LiteralExperiencesvsAbstract: $res<Br>" );
$res = db_query_first_cell( "select LyricalDensity                          from songs limit 1" );
echo( "LyricalDensity: $res<Br>" );
$res = db_query_first_cell( "select IntroLength                             from songs limit 1" );
echo( "IntroLength: $res<Br>" );
$res = db_query_first_cell( "select OutroLength                             from songs limit 1" );
echo( "OutroLength: $res<Br>" );
$res = db_query_first_cell( "select MelodicIntervalPrevalence               from songs limit 1" );
echo( "MelodicIntervalPrevalence: $res<Br>" );
$res = db_query_first_cell( "select UseOf7thChords                          from songs limit 1" );
echo( "UseOf7thChords: $res<Br>" );
$res = db_query_first_cell( "select UseOfMajor7thChords                     from songs limit 1" );
echo( "UseOfMajor7thChords: $res<Br>" );
$res = db_query_first_cell( "select PercentProfanity                        from songs limit 1" );
echo( "PercentProfanity: $res<Br>" );
$res = db_query_first_cell( "select EndLineConsonanceRhymePercentage        from songs limit 1" );
echo( "EndLineConsonanceRhymePercentage: $res<Br>" );
$res = db_query_first_cell( "select SecondaryPerfectRhymesPercentage        from songs limit 1" );
echo( "SecondaryPerfectRhymesPercentage: $res<Br>" );
$res = db_query_first_cell( "select Danceability                            from songs limit 1" );

$res = db_query_first_cell( "select LoudnessRange                           from songs limit 1" );
echo( "LoudnessRange: $res<Br>" );
